Delete DOCKER_CONFIG and INHERIT_IMAGEPULLSECRETS from dev/e2e test scripts (#2168)

diff --git a/dev/env/scripts/create-imagepullsecrets b/dev/env/scripts/create-imagepullsecrets
--- a/dev/env/scripts/create-imagepullsecrets
+++ b/dev/env/scripts/create-imagepullsecrets
@@ -1,100 +1,51 @@
 #!/usr/bin/env bash
 
-## This script assembles ImagePullSecrets for Quay.io as Kubernetes manifests ready for applying them to a cluster.
+## This script assembles ImagePullSecrets for quay.io and registry.redhat.io as Kubernetes manifests ready for applying them to a cluster.
 
 GITROOT="$(git rev-parse --show-toplevel)"
-export GITROOT
 # shellcheck source=/dev/null
 source "${GITROOT}/dev/env/scripts/lib.sh"
 
-registry="quay.io"
-username="${QUAY_USER:-}"
-password="${QUAY_TOKEN:-}"
-
-if type openssl >/dev/null 2>&1; then
-    b64enc_cmd=(openssl base64)
-elif type base64 >/dev/null 2>&1; then
-    b64enc_cmd=(base64)
-else
-    echo "No base64 command was found on your system!" 1>&2
-    exit 1
-fi
-
-if ! "${b64enc_cmd[@]}" </dev/null >/dev/null 2>&1; then
-    echo >&2 "${b64enc_cmd[*]} command fails to encode an empty string!"
-    exit 1
-fi
-
-if [[ -z "${username}" ]]; then
-    echo -n "Enter quay.io username: "
-    read -r username
-fi
-
-if [[ -z "${password}" ]]; then
-    echo -n "Enter quay.io password: "
-    read -r -s password
-fi
-
-function b64enc() {
-    echo -n "$1" | "${b64enc_cmd[@]}" | tr -d '\n'
-}
-
-function url2std() {
-    tr '_-' '/+' | tr -d '\n'
-}
-
-function std2url() {
-    tr '/+' '_-' | tr -d '\n'
-}
-
-function mkauth() {
-    local username="$1"
-    local password="$2"
-
-    b64enc "${username}:${password}" | std2url
-    return $?
-}
-
-function print_auth() {
-    local auth_token="$1"
-    if [[ -z $auth_token ]]; then
-        return 1
-    fi
-    local auth_token_std
-    auth_token_std=$(url2std <<<"$auth_token")
-    local auths_str="{\"auths\":{\"$registry\":{\"auth\":\"${auth_token_std}\"}}}"
-    b64enc "$auths_str"
-    return $?
-}
-
-registry_auth="$(print_auth "$(mkauth "${username}" "${password}")")"
-
-log "Creating rhacs-registry image pull secret in namespace ${STACKROX_OPERATOR_NAMESPACE}"
-    resOperatorImage=$(
-        cat <<EOF
-apiVersion: v1
-data:
-  .dockerconfigjson: ${registry_auth}
-kind: Secret
-metadata:
-  name: rhacs-registry
-  namespace: ${STACKROX_OPERATOR_NAMESPACE}
-type: kubernetes.io/dockerconfigjson
-EOF
-    )
-    echo "$resOperatorImage" | $KUBECTL -n "$STACKROX_OPERATOR_NAMESPACE" apply -f -
-
-log "Creating quay-ips image pull secret in namespace ${ACSCS_NAMESPACE}"
-res=$(
+print_pull_secret() {
+    local name="$1"
+    [[ -n "$name" ]] || die "Image pull secret name is empty"
+    local registry_auth="$2"
+    [[ -n "$registry_auth" ]] || die "Unable to create an image pull secret with name $name: .dockerconfigjson is empty"
     cat <<EOF
 apiVersion: v1
 data:
   .dockerconfigjson: ${registry_auth}
 kind: Secret
 metadata:
-  name: quay-ips
-  namespace: $ACSCS_NAMESPACE
+  name: $name
 type: kubernetes.io/dockerconfigjson
 EOF
-)
-echo "$res" | $KUBECTL -n "$ACSCS_NAMESPACE" apply -f -
+}
+
+redhat_registry_auth() {
+    # Try to fetch an access token from ocm.
+    local registry_auth
+    registry_auth=$(ocm post /api/accounts_mgmt/v1/access_token <<< '' 2>/dev/null | jq -r '. | @base64')
+    if [ -n "$registry_auth" ]; then
+        echo "$registry_auth"
+        return
+    fi
+    # If failed, fallback to retrieving credentials from docker config / cred store.
+    docker_auth.sh -m k8s registry.redhat.io
+}
+
+quay_registry_auth() {
+    REGISTRY_USERNAME="${QUAY_USER:-}" REGISTRY_PASSWORD="${QUAY_TOKEN:-}" docker_auth.sh -m k8s quay.io
+}
+
+# support both registry.redhat.io and quay.io to quickly switch images between upstream and downstream.
+# order is important, the latter takes precedence (overrides) in case the registry is defined in both auth-s
+composite_registry_auth() {
+    echo "$(redhat_registry_auth | base64 -d)" "$(quay_registry_auth | base64 -d)" | jq -s -r 'reduce .[] as $x ({}; . * $x) | @base64'
+}
+
+log "Creating rhacs-registry image pull secret in namespace ${STACKROX_OPERATOR_NAMESPACE}"
+print_pull_secret "rhacs-registry" "$(composite_registry_auth)" | $KUBECTL -n "$STACKROX_OPERATOR_NAMESPACE" apply -f -
+log "Creating redhat-pull-secret image pull secret in namespace rhacs-vertical-pod-autoscaler"
+print_pull_secret "redhat-pull-secret" "$(redhat_registry_auth)" | $KUBECTL -n "rhacs-vertical-pod-autoscaler" apply -f -
+log
