ShellCheck

diff --git a/dev/env/scripts/create-imagepullsecrets-interactive b/dev/env/scripts/create-imagepullsecrets-interactive
--- a/dev/env/scripts/create-imagepullsecrets-interactive
+++ b/dev/env/scripts/create-imagepullsecrets-interactive
@@ -2,7 +2,9 @@
 
 ## This script assembles ImagePullSecrets for Quay.io as Kubernetes manifests ready for applying them to a cluster.
 
-export GITROOT="$(git rev-parse --show-toplevel)"
+GITROOT="$(git rev-parse --show-toplevel)"
+export GITROOT
+# shellcheck source=/dev/null
 source "${GITROOT}/dev/env/scripts/lib.sh"
 init
 
@@ -20,18 +22,18 @@ else
 fi
 
 if ! "${b64enc_cmd[@]}" </dev/null >/dev/null 2>&1; then
-    echo >&2 "${b64_enc_cmd[@]} command fails to encode an empty string!"
+    echo >&2 "${b64enc_cmd[*]} command fails to encode an empty string!"
     exit 1
 fi
 
 if [[ -z "${username}" ]]; then
     echo -n "Enter quay.io username: "
-    read username
+    read -r username
 fi
 
 if [[ -z "${password}" ]]; then
     echo -n "Enter quay.io password: "
-    read -s password
+    read -r -s password
 fi
 
 function b64enc() {
@@ -59,7 +61,8 @@ function print_auth() {
     if [[ -z $auth_token ]]; then
         return 1
     fi
-    local auth_token_std="$(url2std <<<"$auth_token")"
+    local auth_token_std
+    auth_token_std=$(url2std <<<"$auth_token")
     local auths_str="{\"auths\":{\"$registry\":{\"auth\":\"${auth_token_std}\"}}}"
     b64enc "$auths_str"
     return $?
