Refactor RH IPS

diff --git a/dev/env/scripts/create-imagepullsecrets b/dev/env/scripts/create-imagepullsecrets
--- a/dev/env/scripts/create-imagepullsecrets
+++ b/dev/env/scripts/create-imagepullsecrets
@@ -1,15 +1,47 @@
 #!/usr/bin/env bash
 
-## This script assembles ImagePullSecrets for Quay.io as Kubernetes manifests ready for applying them to a cluster.
+## This script assembles ImagePullSecrets for quay.io and registry.redhat.io as Kubernetes manifests ready for applying them to a cluster.
 
 GITROOT="$(git rev-parse --show-toplevel)"
-export GITROOT
 # shellcheck source=/dev/null
 source "${GITROOT}/dev/env/scripts/lib.sh"
 
-registry="quay.io"
+print_pull_secret() {
+    local name="$1"
+    [[ -n "$name" ]] || die "Image pull secret name is empty"
+    local registry_auth="$2"
+    [[ -n "$registry_auth" ]] || die "Unable to create an image pull secret with name $name: .dockerconfigjson is empty"
+    cat <<EOF
+apiVersion: v1
+data:
+  .dockerconfigjson: ${registry_auth}
+kind: Secret
+metadata:
+  name: $name
+type: kubernetes.io/dockerconfigjson
+EOF
+}
+
+quay_registry_auth() {
+    docker_auth.sh -m k8s "quay.io"
+}
+
+redhat_registry_auth() {
+    # Try to fetch an access token from ocm.
+    local registry_auth
+    registry_auth=$(ocm post /api/accounts_mgmt/v1/access_token <<< '' 2>/dev/null | jq '. | @base64')
+    if [ -n "$registry_auth" ]; then
+        echo "$registry_auth"
+        return 0
+    fi
+    # If failed, fallback to retrieving credentials from docker config / cred store.
+    docker_auth.sh -m k8s registry.redhat.io
+}
 
 log "Creating rhacs-registry image pull secret in namespace ${STACKROX_OPERATOR_NAMESPACE}"
-pull_secret.sh "rhacs-registry" "$registry" | $KUBECTL -n "$STACKROX_OPERATOR_NAMESPACE" apply -f -
+print_pull_secret "rhacs-registry" "$(quay_registry_auth)" | $KUBECTL -n "$STACKROX_OPERATOR_NAMESPACE" apply -f -
 log "Creating quay-ips image pull secret in namespace ${ACSCS_NAMESPACE}"
-pull_secret.sh "quay-ips" "$registry" | $KUBECTL -n "$ACSCS_NAMESPACE" apply -f -
+print_pull_secret "quay-ips" "$(quay_registry_auth)" | $KUBECTL -n "$ACSCS_NAMESPACE" apply -f -
+log "Creating redhat-pull-secret image pull secret in namespace rhacs-vertical-pod-autoscaler"
+print_pull_secret "redhat-pull-secret" "$(redhat_registry_auth)" | $KUBECTL -n "rhacs-vertical-pod-autoscaler" apply -f -
+log
